name: CI/CD

on: [push]
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        steps: actions/checkout@v3